### ISSUE TITLE
Allow typing text into a cell

### ISSUE THREAD

**Issue by cjfloss** [ryonakano/Spreadsheet#22] opened 2017-12-27 14:52 UTC
Right now I can't write words into a cell.

**Comment by ryonakano** [comment] 2019-07-23 22:04
Closing as duplicate of #12

**Comment by ryonakano** [comment] 2020-07-11 00:38
I seemed to misunderstand; #12 means texts in formulas, but this seems to mean plain texts in a cell

**Closed** 2020-07-23 00:07 UTC
Labels: Status: Confirmed
